# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # --- ATURAN TAMBAHAN UNTUK STATIC CODE ANALYSIS ---
    # Mewajibkan penggunaan const agar performa lebih cepat
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    
    # Mencegah variabel yang bisa diubah (mutable) jika tidak perlu
    prefer_final_fields: true
    
    # Mencegah penggunaan print() di production (gunakan debugPrint atau logger)
    avoid_print: true 
    
    # Mencegah error umum pada context di async function
    use_build_context_synchronously: true
    
    # Menggunakan single quote (') agar konsisten
    prefer_single_quotes: true