// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMMk7XsdSUzIIXFoBjSVqNPg6q5XZeWwE',
    appId: '1:712677836662:android:fcca57deff4df924365c57',
    messagingSenderId: '712677836662',
    projectId: 'ecohabits-app',
    storageBucket: 'ecohabits-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAGUlKQvtSeynfkKBP5Q9nRP6gGSNyYyY',
    appId: '1:712677836662:ios:d905be18fb8d605e365c57',
    messagingSenderId: '712677836662',
    projectId: 'ecohabits-app',
    storageBucket: 'ecohabits-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqN2NSDISKp0O53zNtO-qV73j64zAmpLI',
    appId: '1:712677836662:web:f55c86885bea40d5365c57',
    messagingSenderId: '712677836662',
    projectId: 'ecohabits-app',
    authDomain: 'ecohabits-app.firebaseapp.com',
    storageBucket: 'ecohabits-app.firebasestorage.app',
    measurementId: 'G-0K114X0LH7',
  );

}